export * from "./SEO"
export * from "./Layout"
export * from "./Hero"
export * from "./Header"
export * from "./About"
export * from "./Boxes"
export * from "./Details"

export * from "./FAQ"
export * from "./Footer"
